[project]
name = "siters"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.11.1",
    "pymupdf>=1.25.2",
    "pyqtdarktheme==2.1.0",
    "pyside6>=6.8.2",
]
